// mockData.js — Shared mock data for CGOE Connect platform

export const users = [
  {
    id: "u1",
    name: "Aisha Patel",
    bio: "MS CS '25 | ML enthusiast | ex-Google",
    profilePic: "https://i.pravatar.cc/150?img=1",
    program: "CGOE",
    classes: ["cs229", "cs231n"],
    savedPosts: ["p2", "p4"],
    role: "student",
    timezone: "America/New_York",
  },
  {
    id: "u2",
    name: "James Wu",
    bio: "HCP student | Healthcare + AI",
    profilePic: "https://i.pravatar.cc/150?img=2",
    program: "HCP",
    classes: ["cs224n"],
    savedPosts: [],
    role: "moderator",
    timezone: "America/Los_Angeles",
  },
  {
    id: "u3",
    name: "Sofia Reyes",
    bio: "MS EE | Signal processing nerd",
    profilePic: "https://i.pravatar.cc/150?img=3",
    program: "MS",
    classes: ["cs229", "ee364a"],
    savedPosts: ["p1"],
    role: "student",
    timezone: "Europe/London",
  },
  {
    id: "u4",
    name: "Derek Okafor",
    bio: "CGOE | Full-stack dev | Building cool things",
    profilePic: "https://i.pravatar.cc/150?img=4",
    program: "CGOE",
    classes: ["cs231n", "cs224n"],
    savedPosts: [],
    role: "student",
    timezone: "America/Chicago",
  },
];

export const classes = [
  {
    id: "cs229",
    name: "CS229 – Machine Learning",
    program: ["CGOE", "MS", "NDO", "Certificate"],
  },
  {
    id: "cs231n",
    name: "CS231N – Deep Learning for Vision",
    program: ["CGOE", "MS", "Professional Ed", "Certificate"],
  },
  {
    id: "cs224n",
    name: "CS224N – NLP with Deep Learning",
    program: ["CGOE", "HCP", "MS", "NDO"],
  },
  {
    id: "ee364a",
    name: "EE364A – Convex Optimization",
    program: ["MS", "Certificate", "Professional Ed"],
  },
  {
    id: "cs145",
    name: "CS145 – Data Management",
    program: ["CGOE", "Professional Ed", "Certificate"],
  },
];

export const chats = [
  {
    id: "ch1",
    classId: "cs229",
    title: "HW1 – Linear Regression",
    tags: ["HW"],
    createdBy: "u1",
    moderatorId: "u2",
    createdAt: "2026-04-01T10:00:00Z",
    pinned: true,
  },
  {
    id: "ch2",
    classId: "cs229",
    title: "Midterm Study Group",
    tags: ["Test"],
    createdBy: "u3",
    moderatorId: null,
    createdAt: "2026-04-10T14:00:00Z",
    pinned: false,
  },
  {
    id: "ch3",
    classId: "cs231n",
    title: "Assignment 2 – CNNs",
    tags: ["HW"],
    createdBy: "u4",
    moderatorId: "u2",
    createdAt: "2026-04-15T09:00:00Z",
    pinned: false,
  },
  {
    id: "ch4",
    classId: "cs224n",
    title: "Yapping about transformers",
    tags: ["Yap"],
    createdBy: "u2",
    moderatorId: null,
    createdAt: "2026-04-20T16:30:00Z",
    pinned: false,
  },
];

export const messages = [
  {
    id: "m1",
    chatId: "ch1",
    authorId: "u1",
    tag: "HW",
    content: "Has anyone started Q3 yet? The math is tripping me up.",
    reactions: [{ emoji: "😅", userIds: ["u3", "u4"] }],
    helpful: 2,
    markedHelpfulBy: ["u3", "u4"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-02T11:00:00Z",
    flagged: false,
  },
  {
    id: "m2",
    chatId: "ch1",
    authorId: "u3",
    tag: "HW",
    content: "Yeah, check the lecture 3 slides — gradient derivation is on slide 22. The key is to vectorize the loss before taking the derivative.",
    reactions: [{ emoji: "🙏", userIds: ["u1"] }, { emoji: "💡", userIds: ["u1", "u4"] }],
    helpful: 5,
    markedHelpfulBy: ["u1", "u2", "u4"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-02T11:15:00Z",
    flagged: false,
  },
  {
    id: "m3",
    chatId: "ch2",
    authorId: "u4",
    tag: "Study",
    content: "Anyone want to do a Zoom session this weekend?",
    reactions: [],
    helpful: 0,
    markedHelpfulBy: [],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-11T10:00:00Z",
    flagged: false,
  },
  {
    id: "m4",
    chatId: "ch1",
    authorId: "u2",
    tag: "HW",
    content: "For Q3, remember to vectorize your gradient computation — a for-loop over training examples will time out on the autograder. numpy broadcasting is your friend here.",
    reactions: [{ emoji: "💯", userIds: ["u1", "u3"] }, { emoji: "👍", userIds: ["u4"] }],
    helpful: 6,
    markedHelpfulBy: ["u1", "u3", "u4"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-02T12:00:00Z",
    flagged: false,
  },
  {
    id: "m5",
    chatId: "ch1",
    authorId: "u3",
    tag: "Resource",
    content: "Here's a diagram I sketched of the gradient flow for the vectorized form. Should make Q3b clearer.",
    reactions: [{ emoji: "🔥", userIds: ["u1", "u2", "u4"] }],
    helpful: 7,
    markedHelpfulBy: ["u1", "u2", "u4"],
    imageUrl: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=700&q=80",
    poll: null,
    scheduler: null,
    createdAt: "2026-04-02T13:00:00Z",
    flagged: false,
  },
  {
    id: "m6",
    chatId: "ch1",
    authorId: "u1",
    tag: "General",
    content: "When should we do an office hours session together?",
    reactions: [],
    helpful: 0,
    markedHelpfulBy: [],
    imageUrl: null,
    poll: {
      question: "Best time for an informal office hours?",
      options: [
        { id: "o1", text: "Thursday 5–6 pm", votes: 4 },
        { id: "o2", text: "Friday 3–4 pm", votes: 2 },
        { id: "o3", text: "Saturday 10 am–noon", votes: 1 },
      ],
      totalVotes: 7,
      votedBy: { u2: 0, u3: 0, u4: 1 },
    },
    scheduler: null,
    createdAt: "2026-04-02T14:00:00Z",
    flagged: false,
  },
  {
    id: "m7",
    chatId: "ch2",
    authorId: "u1",
    tag: "Study",
    content: "Study group locked in — details below. DM me if you can't make it and I'll share notes.",
    reactions: [{ emoji: "🙌", userIds: ["u3", "u4"] }],
    helpful: 2,
    markedHelpfulBy: ["u3", "u4"],
    imageUrl: null,
    poll: null,
    scheduler: {
      title: "CS229 Midterm Study Group",
      date: "2026-05-03",
      time: "14:00",
      location: "Gates B12",
      attendees: ["u1", "u3", "u4"],
    },
    createdAt: "2026-04-11T12:00:00Z",
    flagged: false,
  },
  {
    id: "m8",
    chatId: "ch4",
    authorId: "u2",
    tag: "Yap",
    content: "Hot take: attention is NOT all you need. Positional encodings are doing at least 30% of the heavy lifting and nobody talks about it.",
    reactions: [{ emoji: "😂", userIds: ["u1"] }, { emoji: "💯", userIds: ["u3"] }],
    helpful: 1,
    markedHelpfulBy: ["u3"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-20T17:00:00Z",
    flagged: false,
  },
  {
    id: "m9",
    chatId: "ch4",
    authorId: "u1",
    tag: "Yap",
    content: "I mean... the paper literally says it in the title 😅. But you're not wrong — RoPE embeddings are arguably the most underrated innovation of the past 5 years.",
    reactions: [{ emoji: "😅", userIds: ["u2", "u4"] }, { emoji: "🤔", userIds: ["u3"] }],
    helpful: 0,
    markedHelpfulBy: [],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-20T17:30:00Z",
    flagged: false,
  },
  {
    id: "m10",
    chatId: "ch4",
    authorId: "u4",
    tag: "Yap",
    content: "Can we also talk about how nobody actually reads the full Methods section of the original paper? Everyone's working off blog post summaries.",
    reactions: [{ emoji: "💀", userIds: ["u1", "u2"] }],
    helpful: 3,
    markedHelpfulBy: ["u1", "u2"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-20T18:00:00Z",
    flagged: false,
  },
  // General chat messages
  {
    id: "mg1",
    chatId: "general",
    authorId: "u2",
    tag: "General",
    content: "Welcome to CGOEConnect! 👋 This is the #introductions channel. Share your name, program, and what you're working on this quarter.",
    reactions: [{ emoji: "👋", userIds: ["u1", "u3", "u4"] }],
    helpful: 5,
    markedHelpfulBy: ["u1", "u3", "u4"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-01T09:00:00Z",
    flagged: false,
  },
  {
    id: "mg2",
    chatId: "general",
    authorId: "u1",
    tag: "General",
    content: "Hey everyone! I'm Aisha — CGOE MS CS student based in NYC. Taking CS229 and CS231N this quarter. Really excited to connect with you all! 🎉",
    reactions: [{ emoji: "❤️", userIds: ["u2", "u3"] }, { emoji: "🎉", userIds: ["u4"] }],
    helpful: 3,
    markedHelpfulBy: ["u2", "u3"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-01T10:00:00Z",
    flagged: false,
  },
  {
    id: "mg3",
    chatId: "general",
    authorId: "u3",
    tag: "Question",
    content: "Sofia here — MS EE, signal processing background. Trying to branch into ML this quarter. Any tips for someone coming from EE into CS229?",
    reactions: [{ emoji: "🙏", userIds: ["u1"] }],
    helpful: 1,
    markedHelpfulBy: ["u1"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-01T11:00:00Z",
    flagged: false,
  },
  {
    id: "mg4",
    chatId: "general",
    authorId: "u4",
    tag: "General",
    content: "Derek from CGOE! Full-stack background, now going deep on deep learning 😄. Happy to pair on projects — hit me up if you want to collaborate.",
    reactions: [{ emoji: "🤝", userIds: ["u1", "u2"] }],
    helpful: 2,
    markedHelpfulBy: ["u1", "u2"],
    imageUrl: null,
    poll: null,
    scheduler: null,
    createdAt: "2026-04-01T12:00:00Z",
    flagged: false,
  },
];

export const posts = [
  {
    id: "p1",
    authorId: "u1",
    classId: "cs229",
    chatId: "ch2", // Midterm Study Group subchat
    content: "Just finished the final project — used transformers for time-series. Happy to share notes!",
    upvotes: 12,
    upvotedBy: ["u2", "u3", "u4"],
    comments: ["c1", "c2"],
    saved: false,
    flagged: false,
    createdAt: "2026-04-21T08:00:00Z",
  },
  {
    id: "p2",
    authorId: "u3",
    classId: "cs231n",
    chatId: "ch3", // Assignment 2 – CNNs subchat
    content: "Pro tip: use Google Colab Pro for A2. Local GPU was not cutting it.",
    upvotes: 8,
    upvotedBy: ["u1", "u4"],
    comments: [],
    saved: false,
    flagged: false,
    createdAt: "2026-04-22T12:00:00Z",
  },
  {
    id: "p3",
    authorId: "u2",
    classId: null, // general post
    chatId: null,
    content: "Welcome to the CGOE community! Introduce yourself below 👋",
    upvotes: 24,
    upvotedBy: ["u1", "u3", "u4"],
    comments: ["c3"],
    saved: false,
    flagged: false,
    createdAt: "2026-04-01T09:00:00Z",
  },
  {
    id: "p4",
    authorId: "u4",
    classId: "cs224n",
    chatId: "ch4", // Yapping about transformers subchat
    content: "Anyone else think the attention mechanism section of the lectures could use more examples?",
    upvotes: 6,
    upvotedBy: ["u1"],
    comments: [],
    saved: false,
    flagged: false,
    createdAt: "2026-04-23T15:00:00Z",
  },
];

export const comments = [
  {
    id: "c1",
    postId: "p1",
    authorId: "u3",
    content: "Would love to see those notes! DM me.",
    createdAt: "2026-04-21T09:00:00Z",
    flagged: false,
  },
  {
    id: "c2",
    postId: "p1",
    authorId: "u4",
    content: "Same — this is super helpful context for my project idea.",
    createdAt: "2026-04-21T10:00:00Z",
    flagged: false,
  },
  {
    id: "c3",
    postId: "p3",
    authorId: "u1",
    content: "Hey everyone! CGOE MS CS student here, based in NYC 🗽",
    createdAt: "2026-04-01T10:00:00Z",
    flagged: false,
  },
];

export const reviews = [
  {
    id: "r1",
    classId: "cs229",
    authorId: "u1",
    rating: 4,
    content: "Great course — lectures are dense but rewarding. Workload is heavy.",
    cgoeSpecific: true,
    helpfulVotes: 3,
    createdAt: "2026-03-15T10:00:00Z",
    flagged: false,
  },
  {
    id: "r2",
    classId: "cs231n",
    authorId: "u4",
    rating: 5,
    content: "Best ML course I've taken. A2 is brutal but worth it.",
    cgoeSpecific: false,
    helpfulVotes: 7,
    createdAt: "2026-03-20T10:00:00Z",
    flagged: false,
  },
];

export const flags = [
  {
    id: "f1",
    targetType: "message", // message | post | comment
    targetId: "m1",
    reportedBy: "u2",
    reason: "Off-topic",
    resolved: false,
    createdAt: "2026-04-02T12:00:00Z",
  },
];

// Currently logged-in mock user
export const currentUser = users[0];
